[profile.default]
src = "src"
out = "out"
test = 'test'
libs = ["lib"]
gas_reports = []
cbor_metadata = true

[etherscan]
tenderly_eth_fork_mainnet = { key = "$TENDERLY_ACCESS_KEY", chain = 123456, url = "${TN_FORK_ETH_MAINNET_RPC_URL}/verify/etherscan" }
eth_sepolia = {key = "$SEPOLIA_API_KEY", chain = 11155111, url = "${SEPOLIA_API_URL}"}

[profile.remappings]
remappings = [
    'openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src'
]