[profile.default]
src = "src"
out = "out"
test = 'test'
libs = ["lib"]
gas_reports = []
cbor_metadata = true

ignored_warnings_from = []

[etherscan]

[profile.remappings]
remappings = [
    'openzeppelin/=lib/openzeppelin-contracts/',
    'forge-std/=lib/forge-std/src'
]